name: Quote workflow

on:
  push:
  schedule:
    - cron: '0 */6 * * *'  # Runs every six hours

  workflow_dispatch:

jobs:
  update-readme-with-quote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Ensures authentication
          fetch-depth: 0  

       - name: Fetch Quote
        run: |
          quote=$(curl -s https://api.quotable.io/random | jq -r '.content')
          echo "Fetched Quote: $quote"
          awk -v quote="$quote" '
          /<!-- QUOTE:START -->/ {print; print quote; found=1; next}
          /<!-- QUOTE:END -->/ {found=0}
          !found' README.md > temp.md && mv temp.md README.md


      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Updated Quote" || exit 0
          git push origin main
