name: Quote workflow

on:
  push:
  schedule:
    - cron: '0 */6 * * *'  # Runs every six hours

  workflow_dispatch:

jobs:
  update-readme-with-quote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch Quote from Stoicism API
        run: |
          response=$(curl -s https://stoic.tekkloon.net/stoic-quote)
          quote=$(echo "$response" | jq -r '.data.quote')
          author=$(echo "$response" | jq -r '.data.author')
          full_quote="$quote - $author"
          echo "Fetched Quote: $full_quote"

          if [ -n "$quote" ]; then
            awk -v quote="$full_quote" '
            /<!-- QUOTE:START -->/ {print; print quote; found=1; next}
            /<!-- QUOTE:END -->/ {found=0}
            !found' README.md > temp.md && mv temp.md README.md
          else
            echo "No quote fetched!"
            exit 1
          fi

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Updated Quote from Stoicism API" || exit 0
          git push origin main
