name: Quote workflow

on:
  push:
  schedule:
    - cron: '0 */6 * * *'

  workflow_dispatch:

jobs:
  update-readme-with-quote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch Quote
        run: |
          curl -s https://api.quotable.io/random | jq -r '.content' > quote.txt
          sed -i '/<!-- QUOTE:START -->/,/<!-- QUOTE:END -->/c\<!-- QUOTE:START -->\n'"$(cat quote.txt)"'\n<!-- QUOTE:END -->' README.md

            - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Updated Quote" || exit 0
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git

